<?php 
 function getUserLevel($level){ if($level){ $info = D('SystemGroup')->where('id='.$level)->find(); return '<font color="red">'.$info['name'].'</font>'; }else{ return '普通用户'; } } function getInfoCate($id){ $value = D('InfoCate')->where("id=".$id)->find(); return $value['name']; } function formatsize($fileSize) { $size = sprintf("%u", $fileSize); if($size == 0) { return("0 Bytes"); } $sizename = array(" Bytes", " KB", " MB", " GB", " TB", " PB", " EB", " ZB", " YB"); return round($size/pow(1024, ($i = floor(log($size, 1024)))), 2) . $sizename[$i]; } 
return array (
  'dispatch_on' => true,
  'url_model' => 3,
  'path_model' => 2,
  'path_depr' => '/',
  'router_on' => true,
  'check_file_case' => false,
  'tag_plugin_on' => false,
  'session_auto_start' => true,
  'web_log_record' => false,
  'log_record_level' => 
  array (
    0 => 'EMERG',
    1 => 'ALERT',
    2 => 'CRIT',
    3 => 'ERR',
  ),
  'log_file_size' => 2097152,
  'debug_mode' => false,
  'error_message' => '您浏览的页面暂时发生了错误！请稍后再试～',
  'error_page' => '',
  'show_error_msg' => true,
  'var_pathinfo' => 's',
  'var_module' => 'm',
  'var_action' => 'a',
  'var_page' => 'p',
  'var_template' => 't',
  'var_language' => 'l',
  'var_ajax_submit' => 'ajax',
  'default_module' => 'Index',
  'default_action' => 'index',
  'tmpl_cache_on' => true,
  'tmpl_cache_time' => -1,
  'tmpl_switch_on' => true,
  'auto_detect_theme' => false,
  'default_template' => 'default',
  'template_suffix' => '.html',
  'cachfile_suffix' => '.php',
  'output_charset' => 'utf-8',
  'tmpl_var_identify' => 'array',
  'page_numbers' => 5,
  'list_numbers' => 20,
  'auto_name_identify' => true,
  'default_model_app' => '@',
  'html_file_suffix' => '.shtml',
  'html_cache_on' => false,
  'html_cache_time' => 60,
  'html_read_type' => 1,
  'html_url_suffix' => '',
  'time_zone' => 'PRC',
  'lang_switch_on' => false,
  'default_language' => 'zh-cn',
  'auto_detect_lang' => false,
  'db_charset' => 'utf8',
  'db_deploy_type' => 0,
  'db_rw_separate' => false,
  'db_fields_cache' => true,
  'data_cache_time' => -1,
  'data_cache_compress' => false,
  'data_cache_check' => false,
  'data_cache_type' => 'File',
  'data_cache_path' => 'E:/wamp/www/thinksns//runtime/admin/Temp/',
  'data_cache_subdir' => false,
  'data_path_level' => 1,
  'cache_serial_header' => '<?php
//',
  'cache_serial_footer' => '
?>',
  'show_run_time' => false,
  'show_adv_time' => false,
  'show_db_times' => false,
  'show_cache_times' => false,
  'show_use_mem' => false,
  'show_page_trace' => false,
  'tmpl_engine_type' => 'Think',
  'tmpl_deny_func_list' => 'echo,exit',
  'tmpl_l_delim' => '{',
  'tmpl_r_delim' => '}',
  'taglib_begin' => '<',
  'taglib_end' => '>',
  'tag_nested_level' => 3,
  'taglib_list' => 'cx,html',
  'cookie_expire' => 3600,
  'cookie_domain' => '',
  'cookie_path' => '/',
  'cookie_prefix' => '',
  'ajax_return_type' => 'JSON',
  'auto_load_path' => 'Think.Util.',
  'action_jump_tmpl' => 'THEME_PATH&success',
  'action_404_tmpl' => 'Public:404',
  'app_domain_deploy' => false,
  'extend_config_list' => 
  array (
    0 => 'taglibs',
    1 => 'routes',
    2 => 'tags',
    3 => 'htmls',
    4 => 'modules',
    5 => 'actions',
  ),
  'trace_tmpl_file' => 'E:/wamp/www/thinksns//thinkphp/Tpl/PageTrace.tpl.php',
  'exception_tmpl_file' => 'E:/wamp/www/thinksns//thinkphp/Tpl/ThinkException.tpl.php',
  'db_type' => 'mysql',
  'db_host' => 'localhost',
  'db_name' => 'xysns',
  'db_user' => 'deroot',
  'db_pwd' => 'dedata',
  'db_prefix' => 'ts_',
  'cache_data' => 'E:/wamp/www/thinksns//data/cache/secache_data',
  'ts_url' => 'http://localhost/thinksns',
  'upload_path' => 'E:/wamp/www/thinksns//data/uploads/',
  'upload_url' => 'http://localhost/thinksns/data/uploads/',
  'token_on' => true,
  'token_name' => 'thinksns_html_token',
  'token_type' => 'md5',
  'other_token' => 'js',
  '_tags_before_login' => 
  array (
    0 => 'ubb',
  ),
);
?>