<?php 
function get_photo_url($savepath) { $path = str_ireplace(UPLOAD_PATH,'',$savepath); $path = UPLOAD_URL.$path; return $path; } function get_photo_path($savepath) { $path = str_ireplace(UPLOAD_PATH,'',$savepath); $path = UPLOAD_PATH.$path; return $path; } function get_photo_filename($filename) { return substr($filename,'0',strpos($filename,'.')); } function get_album_cover($albumId,$albumInfo='') { if(empty($albumInfo) || $albumId!=$albumInfo['id']){ $albumInfo = D('Album')->find($albumId); } if(intval($albumInfo['photoCount'])>0 && !empty($albumInfo['coverImagePath'])){ $cover = SITE_URL.'/thumb.php?w=120&h=100&url='.get_photo_url($albumInfo['coverImagePath']); }else{ $cover = APP_PUBLIC_URL.'/images/photo_zwzp.gif'; } if($albumInfo['privacy']==4){ $cover = APP_PUBLIC_URL.'/images/photo_mima.gif'; }elseif($albumInfo['privacy']==3){ $cover = APP_PUBLIC_URL.'/images/photo_zrkj.gif'; }elseif($albumInfo['privacy']==2){ $cover = APP_PUBLIC_URL.'/images/photo_hykj.gif'; } return $cover; } function get_album_privacy($albumId,$privacy=0) { if($privacy==0){ $albumInfo = D('Album')->find($albumId); $privacy = $albumInfo['privacy']; } return get_privacy($privacy); } function get_privacy_code($privacy) { if($privacy==4){ return 'password'; }elseif($privacy==3){ return 'self'; }elseif($privacy==2){ return 'friend'; }else{ return 'everyone'; } } function get_privacy($privacy) { if($privacy==4){ return '持密码可见'; }elseif($privacy==3){ return '仅主人可见'; }elseif($privacy==2){ return '仅朋友可见'; }else{ return '任何人都可见'; } } function check_relationship($uid,$mid=0) { $api = new TS_API(); if(!$mid){ $mid = $api->user_getLoggedInUser(); } if($uid==$mid){ return 'self'; }elseif($api->friend_areFriends($uid,$mid)){ return 'friend'; }else{ return 'stranger'; } } 
 function GetImageInfoVal($ImageInfo,$val_arr) { $InfoVal = "未知"; foreach($val_arr as $name=>$val) { if ($name==$ImageInfo) { $InfoVal = &$val; break; } } return $InfoVal; } function GetImageInfo($img) { $imgtype = array("", "GIF", "JPG", "PNG", "SWF", "PSD", "BMP", "TIFF(intel byte order)", "TIFF(motorola byte order)", "JPC", "JP2", "JPX", "JB2", "SWC", "IFF", "WBMP", "XBM"); $Orientation = array("", "top left side", "top right side", "bottom right side", "bottom left side", "left side top", "right side top", "right side bottom", "left side bottom"); $ResolutionUnit = array("", "", "英寸", "厘米"); $YCbCrPositioning = array("", "the center of pixel array", "the datum point"); $ExposureProgram = array("未定义", "手动", "标准程序", "光圈先决", "快门先决", "景深先决", "运动模式", "肖像模式", "风景模式"); $MeteringMode_arr = array( "0" => "未知", "1" => "平均", "2" => "中央重点平均测光", "3" => "点测", "4" => "分区", "5" => "评估", "6" => "局部", "255" => "其他" ); $Lightsource_arr = array( "0" => "未知", "1" => "日光", "2" => "荧光灯", "3" => "钨丝灯", "10" => "闪光灯", "17" => "标准灯光A", "18" => "标准灯光B", "19" => "标准灯光C", "20" => "D55", "21" => "D65", "22" => "D75", "255" => "其他" ); $Flash_arr = array( "0" => "flash did not fire", "1" => "flash fired", "5" => "flash fired but strobe return light not detected", "7" => "flash fired and strobe return light detected", ); $exif = @exif_read_data ($img,"IFD0"); if ($exif===false) { $new_img_info = array ("文件信息" => "没有图片EXIF信息"); }else{ $exif = @exif_read_data ($img,0,true); $new_img_info = array ( "文件信息" => "-----------------------------", "文件名" => $exif['FILE']['FileName'], "文件类型" => $imgtype[$exif['FILE']['FileType']], "文件格式" => $exif['FILE']['MimeType'], "文件大小" => $exif['FILE']['FileSize'], "时间戳" => date("Y-m-d H:i:s",$exif['FILE']['FileDateTime']), "图像信息" => "-----------------------------", "图片说明" => $exif['IFD0']['ImageDescription'], "制造商" => $exif['IFD0']['Make'], "型号" => $exif['IFD0']['Model'], "方向" => $Orientation[$exif['IFD0']['Orientation']], "水平分辨率" => $exif['IFD0']['XResolution'].$ResolutionUnit[$exif['IFD0']['ResolutionUnit']], "垂直分辨率" => $exif['IFD0']['YResolution'].$ResolutionUnit[$exif['IFD0']['ResolutionUnit']], "创建软件" => $exif['IFD0']['Software'], "修改时间" => $exif['IFD0']['DateTime'], "作者" => $exif['IFD0']['Artist'], "YCbCr位置控制" => $YCbCrPositioning[$exif['IFD0']['YCbCrPositioning']], "版权" => $exif['IFD0']['Copyright'], "摄影版权" => $exif['COMPUTED']['Copyright.Photographer'], "编辑版权" => $exif['COMPUTED']['Copyright.Editor'], "拍摄信息" => "-----------------------------", "Exif版本" => $exif['EXIF']['ExifVersion'], "FlashPix版本" => "Ver. ".number_format($exif['EXIF']['FlashPixVersion']/100,2), "拍摄时间" => $exif['EXIF']['DateTimeOriginal'], "数字化时间" => $exif['EXIF']['DateTimeDigitized'], "拍摄分辨率高" => $exif['COMPUTED']['Height'], "拍摄分辨率宽" => $exif['COMPUTED']['Width'], "光圈" => $exif['EXIF']['ApertureValue'], "快门速度" => $exif['EXIF']['ShutterSpeedValue'], "快门光圈" => $exif['COMPUTED']['ApertureFNumber'], "最大光圈值" => "F".$exif['EXIF']['MaxApertureValue'], "曝光时间" => $exif['EXIF']['ExposureTime'], "F-Number" => $exif['EXIF']['FNumber'], "测光模式" => GetImageInfoVal($exif['EXIF']['MeteringMode'],$MeteringMode_arr), "光源" => GetImageInfoVal($exif['EXIF']['LightSource'], $Lightsource_arr), "闪光灯" => GetImageInfoVal($exif['EXIF']['Flash'], $Flash_arr), "曝光模式" => ($exif['EXIF']['ExposureMode']==1?"手动":"自动"), "白平衡" => ($exif['EXIF']['WhiteBalance']==1?"手动":"自动"), "曝光程序" => $ExposureProgram[$exif['EXIF']['ExposureProgram']], "曝光补偿" => $exif['EXIF']['ExposureBiasValue']."EV", "ISO感光度" => $exif['EXIF']['ISOSpeedRatings'], "分量配置" => (bin2hex($exif['EXIF']['ComponentsConfiguration'])=="01020300"?"YCbCr":"RGB"), "图像压缩率" => $exif['EXIF']['CompressedBitsPerPixel']."Bits/Pixel", "对焦距离" => $exif['COMPUTED']['FocusDistance']."m", "焦距" => $exif['EXIF']['FocalLength']."mm", "等价35mm焦距" => $exif['EXIF']['FocalLengthIn35mmFilm']."mm", "用户注释编码" => $exif['COMPUTED']['UserCommentEncoding'], "用户注释" => $exif['COMPUTED']['UserComment'], "色彩空间" => ($exif['EXIF']['ColorSpace']==1?"sRGB":"Uncalibrated"), "Exif图像宽度" => $exif['EXIF']['ExifImageLength'], "Exif图像高度" => $exif['EXIF']['ExifImageWidth'], "文件来源" => (bin2hex($exif['EXIF']['FileSource'])==0x03?"digital still camera":"unknown"), "场景类型" => (bin2hex($exif['EXIF']['SceneType'])==0x01?"A directly photographed image":"unknown"), ); } return $new_img_info; } 
return array (
  'dispatch_on' => true,
  'url_model' => 3,
  'path_model' => 2,
  'path_depr' => '/',
  'router_on' => true,
  'check_file_case' => false,
  'tag_plugin_on' => false,
  'session_auto_start' => true,
  'web_log_record' => false,
  'log_record_level' => 
  array (
    0 => 'EMERG',
    1 => 'ALERT',
    2 => 'CRIT',
    3 => 'ERR',
  ),
  'log_file_size' => 2097152,
  'debug_mode' => false,
  'error_message' => '您浏览的页面暂时发生了错误！请稍后再试～',
  'error_page' => '',
  'show_error_msg' => true,
  'var_pathinfo' => 's',
  'var_module' => 'm',
  'var_action' => 'a',
  'var_page' => 'p',
  'var_template' => 't',
  'var_language' => 'l',
  'var_ajax_submit' => 'ajax',
  'default_module' => 'Index',
  'default_action' => 'index',
  'tmpl_cache_on' => true,
  'tmpl_cache_time' => -1,
  'tmpl_switch_on' => true,
  'auto_detect_theme' => false,
  'default_template' => 'default',
  'template_suffix' => '.html',
  'cachfile_suffix' => '.php',
  'output_charset' => 'utf-8',
  'tmpl_var_identify' => 'array',
  'page_numbers' => 5,
  'list_numbers' => 20,
  'auto_name_identify' => true,
  'default_model_app' => '@',
  'html_file_suffix' => '.shtml',
  'html_cache_on' => false,
  'html_cache_time' => 60,
  'html_read_type' => 1,
  'html_url_suffix' => '',
  'time_zone' => 'PRC',
  'lang_switch_on' => true,
  'default_language' => 'zh-cn',
  'auto_detect_lang' => false,
  'db_charset' => 'utf8',
  'db_deploy_type' => 0,
  'db_rw_separate' => false,
  'db_fields_cache' => true,
  'data_cache_time' => -1,
  'data_cache_compress' => false,
  'data_cache_check' => false,
  'data_cache_type' => 'File',
  'data_cache_path' => 'E:/wamp/www/thinksns//runtime/photo/Temp/',
  'data_cache_subdir' => false,
  'data_path_level' => 1,
  'cache_serial_header' => '<?php
//',
  'cache_serial_footer' => '
?>',
  'show_run_time' => false,
  'show_adv_time' => false,
  'show_db_times' => false,
  'show_cache_times' => false,
  'show_use_mem' => false,
  'show_page_trace' => false,
  'tmpl_engine_type' => 'Think',
  'tmpl_deny_func_list' => 'echo,exit',
  'tmpl_l_delim' => '{',
  'tmpl_r_delim' => '}',
  'taglib_begin' => '<',
  'taglib_end' => '>',
  'tag_nested_level' => 3,
  'taglib_list' => 'cx,html',
  'cookie_expire' => 3600,
  'cookie_domain' => '',
  'cookie_path' => '/',
  'cookie_prefix' => '',
  'ajax_return_type' => 'JSON',
  'auto_load_path' => 'Think.Util.',
  'action_jump_tmpl' => 'THEME_PATH&success',
  'action_404_tmpl' => 'Public:404',
  'app_domain_deploy' => false,
  'extend_config_list' => 
  array (
    0 => 'taglibs',
    1 => 'routes',
    2 => 'tags',
    3 => 'htmls',
    4 => 'modules',
    5 => 'actions',
  ),
  'trace_tmpl_file' => 'E:/wamp/www/thinksns//thinkphp/Tpl/PageTrace.tpl.php',
  'exception_tmpl_file' => 'E:/wamp/www/thinksns//thinkphp/Tpl/ThinkException.tpl.php',
  'db_type' => 'mysql',
  'db_host' => 'localhost',
  'db_name' => 'xysns',
  'db_user' => 'deroot',
  'db_pwd' => 'dedata',
  'db_prefix' => 'ts_',
  'cache_data' => 'E:/wamp/www/thinksns//data/cache/secache_data',
  'ts_url' => 'http://localhost/thinksns',
  'upload_path' => 'E:/wamp/www/thinksns//data/uploads/',
  'upload_url' => 'http://localhost/thinksns/data/uploads/',
  'token_on' => true,
  'token_name' => 'thinksns_html_token',
  'token_type' => 'md5',
  'other_token' => 'js',
  '_routes_' => 
  array (
    'album' => 
    array (
      0 => 'Index',
      1 => 'album',
      2 => 'id,uid',
    ),
    'photo' => 
    array (
      0 => 'Index',
      1 => 'photo',
      2 => 'id,aid,uid',
    ),
  ),
);
?>